// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimerMode } from "./TimerMode";

export interface GetSettingsResponse { cycles: number, work_duration: number, relax_duration: number, long_relax_duration: number, mode: TimerMode, }