// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SettingsPayload { work_duration_secs: number, relax_duration_secs: number, long_relax_duration_secs: number, toggle_timer_shortcut: string | null, }