// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimerMode } from "./TimerMode";

export type TimerStatePayload = { mode: TimerMode, cycle: number, is_ended: boolean, duration_secs: number, };
