// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TimerMode } from "./TimerMode";

export interface TimerEndPayload { mode: TimerMode, cycle: number, is_running: boolean, }