on:
  push:
    tags:
      - '*'

name: Build release artifacts

env:
  RUST_BACKTRACE: 1
  CARGO_PROFILE_DEV_DEBUG: 0

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - host: macos-latest
            target: aarch64-apple-darwin
          - host: macos-latest
            target: x86_64-apple-darwin
          - host: windows-latest
            target: x86_64-pc-windows-msvc

    runs-on: ${{ matrix.platform.host }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        uses: ./.github/actions/setup-env
      - name: Add target
        run: rustup target add ${{ matrix.platform.target }}
      - name: Create release
        uses: tauri-apps/tauri-action@v0
        with:
          includeUpdaterJson: true
          tagName: v__VERSION__
          releaseName: 'v__VERSION__'
          args: --target ${{ matrix.platform.target }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_UPDATER_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_UPDATER_PASSWORD }}
