# on: workflow_dispatch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
name: Release

env:
  RUST_BACKTRACE: 1
  CARGO_PROFILE_DEV_DEBUG: 0

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup environment
        uses: ./.github/actions/setup-env
      - name: Create release
        uses: tauri-apps/tauri-action@v0
        with:
          includeUpdaterJson: true
          tagName: v__VERSION__
          releaseName: 'v__VERSION__'
          releaseDraft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_UPDATER_PRIVATE_KEY }}
          TAURI_PASSWORD: ${{ secrets.TAURI_UPDATER_PASSWORD }}
